export const TELE_PERM = [
  {
    id: 1,
    label: "Lead Base Count Distribution",
    contentColor: "--lgi-teal",
    innerRadius: 82,
    // labels: ["first", "second", "third"],
    // data: [80, 40, 73],
    datas: [
      {
        id: 1,
        label: "first1",
        perfomCount: 20,
        bgcolor: "rgba(255, 208, 0, 1)",
      },
      {
        id: 2,
        label: "second2",
        perfomCount: 40,
        bgcolor: "rgba(6, 116, 140, 1)",
      },
    ],
    inerContent: [
      {
        content: "200/200",
        fontSize: 10,
        fontWeight: "bold",
        color: "#000",
      },
      {
        content: "100%",
        fontSize: 12,
        fontWeight: "normal",
        color: "rgba(29, 27, 32, 0.8)",
      },
      {
        content: "Attempts",
        fontSize: 11,
        fontWeight: "normal",
        color: "#000",
      },
    ],
  },
  {
    id: 2,
    label: "Renewed Policy Distribution",
    contentColor: "--lgi-teal",
    innerRadius: 82,
    // labels: ["first", "second", "third"],
    // data: [80, 40, 73],
    datas: [
      {
        id: 1,
        label: "first1",
        perfomCount: 30,
        bgcolor: "rgba(255, 208, 0, 1)",
      },
      {
        id: 2,
        label: "second2",
        perfomCount: 40,
        bgcolor: "rgba(6, 116, 140, 1)",
      },
    ],
    inerContent: [
      {
        content: "200/200",
        fontSize: 10,
        fontWeight: "bold",
        color: "#000",
      },
      {
        content: "100%",
        fontSize: 12,
        fontWeight: "normal",
        color: "rgba(29, 27, 32, 0.8)",
      },
      {
        content: "Attempts",
        fontSize: 11,
        fontWeight: "normal",
        color: "#000",
      },
    ],
  },
  {
    id: 3,
    label: "Total Lead Distribution",
    contentColor: "--lgi-teal",
    innerRadius: 82,
    // labels: ["first", "second", "third"],
    // data: [80, 40, 73],
    datas: [
      {
        id: 1,
        label: "first1",
        perfomCount: 80,
        bgcolor: "rgba(255, 208, 0, 1)",
      },
      {
        id: 2,
        label: "second2",
        perfomCount: 80,
        bgcolor: "rgba(6, 116, 140, 1)",
      },
    ],
    inerContent: [
      {
        content: "200/200",
        fontSize: 10,
        fontWeight: "bold",
        color: "#000",
      },
      {
        content: "100%",
        fontSize: 12,
        fontWeight: "normal",
        color: "rgba(29, 27, 32, 0.8)",
      },
      {
        content: "Attempts",
        fontSize: 11,
        fontWeight: "normal",
        color: "#000",
      },
    ],
  },
];

export const PERFORMACE_SALES = [
  {
    id: 1,
    userID: "LY008",
    userName: "Jai Shree",
    roleName: "Telecaller",
    mobileNo: "+91 98552 01456",
    emailAddress: "rameshy@gmail.com",
    reportingPerson: "Shivani Shinde",
    assignedProduct: "Motor Insurance",
    assignedLeads: 40,
    status: "Active",
  },
  {
    id: 2,
    userID: "LY008",
    userName: "Jai Shree",
    roleName: "Telecaller",
    mobileNo: "+91 98552 01456",
    emailAddress: "rameshy@gmail.com",
    reportingPerson: "Shivani Shinde",
    assignedProduct: "Motor Insurance",
    assignedLeads: 40,
    status: "Active",
  },
  {
    id: 3,
    userID: "LY008",
    userName: "Jai Shree",
    roleName: "Telecaller",
    mobileNo: "+91 98552 01456",
    emailAddress: "rameshy@gmail.com",
    reportingPerson: "Shivani Shinde",
    assignedProduct: "Motor Insurance",
    assignedLeads: 40,
    status: "Active",
  },
];

export const TOP_PERFOMAR = [
  {
    SalesManager: "Radhika Mishra",
    Alloted: 441,
    Attempted: 29,
    Contacts: 27,
    Bookings: 0,
    Reschedules: 6,
    NoRenewal: 0,
    Remind: "7/8",
    NoShow: "0/0",
    ConversionRate: 50,
    Status: "Active",
  },
  {
    SalesManager: "Radhika Mishra",
    Alloted: 441,
    Attempted: 29,
    Contacts: 27,
    Bookings: 0,
    Reschedules: 6,
    NoRenewal: 0,
    Remind: "7/8",
    NoShow: "0/0",
    ConversionRate: 50,
    Status: "Active",
  },
  {
    SalesManager: "Radhika Mishra",
    Alloted: 441,
    Attempted: 29,
    Contacts: 27,
    Bookings: 0,
    Reschedules: 6,
    NoRenewal: 0,
    Remind: "7/8",
    NoShow: "0/0",
    ConversionRate: 50,
    Status: "Inactive",
  },
  {
    SalesManager: "Radhika Mishra",
    Alloted: 441,
    Attempted: 29,
    Contacts: 27,
    Bookings: 0,
    Reschedules: 6,
    NoRenewal: 0,
    Remind: "7/8",
    NoShow: "0/0",
    ConversionRate: 50,
    Status: "Inactive",
  },
];

export const CALLING_OVERVIEW = [
  {
    id: 1,
    label: "deiuw",
    contentColor: "--lgi-teal",
    innerRadius: 82,
    // labels: ["first", "second", "third"],
    // data: [80, 40, 73],
    datas: [
      {
        id: 1,
        label: "first1",
        perfomCount: 120,
        bgcolor: "rgba(66, 133, 244, 1)",
      },
      {
        id: 2,
        label: "second2",
        perfomCount: 0,
        bgcolor: "rgba(235, 235, 235, 1)",
      },
    ],
    inerContent: [
      {
        content: "Reminder",
        fontSize: 11,
        fontWeight: "normal",
        color: "#000",
      },
      // {
      //   content: "200/200",
      //   fontSize: 10,
      //   fontWeight: "bold",
      //   color: "#000",
      // },
      {
        content: "100%",
        fontSize: 12,
        fontWeight: "normal",
        color: "rgba(29, 27, 32, 0.8)",
      },
    ],
  },
  {
    id: 1,
    label: "deiuw",
    contentColor: "--lgi-teal",
    innerRadius: 82,
    // labels: ["first", "second", "third"],
    // data: [80, 40, 73],
    datas: [
      {
        id: 1,
        label: "first1",
        perfomCount: 80,
        bgcolor: "rgba(149, 153, 241, 1)",
      },
      {
        id: 2,
        label: "second2",
        perfomCount: 20,
        bgcolor: "rgba(235, 235, 235, 1)",
      },
    ],
    inerContent: [
      {
        content: "Attempts",
        fontSize: 11,
        fontWeight: "normal",
        color: "#000",
      },
      // {
      //   content: "200/200",
      //   fontSize: 10,
      //   fontWeight: "bold",
      //   color: "#000",
      // },
      {
        content: "90%",
        fontSize: 12,
        fontWeight: "normal",
        color: "rgba(29, 27, 32, 0.8)",
      },
    ],
  },
  {
    id: 1,
    label: "deiuw",
    contentColor: "--lgi-teal",
    innerRadius: 82,
    // labels: ["first", "second", "third"],
    // data: [80, 40, 73],
    datas: [
      {
        id: 1,
        label: "first1",
        perfomCount: 75,
        bgcolor: "rgba(255, 214, 110, 1)",
      },
      {
        id: 2,
        label: "second2",
        perfomCount: 25,
        bgcolor: "rgba(235, 235, 235, 1)",
      },
    ],
    inerContent: [
      {
        content: "Contacts",
        fontSize: 11,
        fontWeight: "normal",
        color: "#000",
      },
      // {
      //   content: "200/200",
      //   fontSize: 10,
      //   fontWeight: "bold",
      //   color: "#000",
      // },
      {
        content: "60%",
        fontSize: 12,
        fontWeight: "normal",
        color: "rgba(29, 27, 32, 0.8)",
      },
    ],
  },
  {
    id: 1,
    label: "deiuw",
    contentColor: "--lgi-teal",
    innerRadius: 82,
    // labels: ["first", "second", "third"],
    // data: [80, 40, 73],
    datas: [
      {
        id: 1,
        label: "first1",
        perfomCount: 1,
        bgcolor: "rgba(255, 110, 110, 1)",
      },
      {
        id: 2,
        label: "second2",
        perfomCount: 99,
        bgcolor: "rgba(235, 235, 235)",
      },
    ],
    inerContent: [
      {
        content: "No Show",
        fontSize: 11,
        fontWeight: "normal",
        color: "#000",
      },
      // {
      //   content: "200/200",
      //   fontSize: 10,
      //   fontWeight: "bold",
      //   color: "#000",
      // },
      {
        content: "0%",
        fontSize: 12,
        fontWeight: "normal",
        color: "rgba(29, 27, 32, 0.8)",
      },
    ],
  },
  {
    id: 1,
    label: "deiuw",
    contentColor: "--lgi-teal",
    innerRadius: 82,
    // labels: ["first", "second", "third"],
    // data: [80, 40, 73],
    datas: [
      {
        id: 1,
        label: "first1",
        perfomCount: 10,
        bgcolor: "rgba(88, 205, 114, 1)",
      },
      {
        id: 2,
        label: "second2",
        perfomCount: 90,
        bgcolor: "rgba(235, 235, 235, 1)",
      },
    ],
    inerContent: [
      {
        content: "Bookings",
        fontSize: 11,
        fontWeight: "normal",
        color: "#000",
      },
      // {
      //   content: "200/200",
      //   fontSize: 10,
      //   fontWeight: "bold",
      //   color: "#000",
      // },
      {
        content: "20%",
        fontSize: 12,
        fontWeight: "normal",
        color: "rgba(29, 27, 32, 0.8)",
      },
    ],
  },
];
